# Generated by Django 3.2.3 on 2021-06-03 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameDrink', models.CharField(max_length=50, verbose_name='Nazwa drinku')),
                ('taste', models.CharField(choices=[('S', 'słodki'), ('B', 'gorzki'), ('R', 'kwaśny')], default='S', max_length=2, verbose_name='Smak drinka')),
                ('temperature', models.CharField(choices=[('W', 'ciepły'), ('C', 'zimny')], default='C', max_length=2, verbose_name='Temperatura')),
                ('ingredientsProportion', models.TextField(verbose_name='Składniki')),
                ('descriptionPreparing', models.TextField(verbose_name='Opis przygotowania')),
                ('photo', models.ImageField(default='some photo', upload_to='uploads/', verbose_name='Zdjęcie drinka')),
            ],
        ),
        migrations.CreateModel(
            name='OtherDrink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otherdrink', models.CharField(blank=True, max_length=20, verbose_name='Inne napoje')),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='napoj', to='searchdrink.drink')),
            ],
        ),
        migrations.CreateModel(
            name='OtherAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otheradd', models.CharField(blank=True, max_length=30, verbose_name='Inne dodatki')),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inne', to='searchdrink.drink')),
            ],
        ),
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fruit', models.CharField(blank=True, max_length=20, verbose_name='Owoce')),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owoc', to='searchdrink.drink')),
            ],
        ),
        migrations.CreateModel(
            name='Alcohol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alcohol', models.CharField(blank=True, max_length=20, verbose_name='Alkohol')),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alko', to='searchdrink.drink')),
            ],
        ),
    ]
