# Generated by Django 3.2.3 on 2021-05-28 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameDrink', models.CharField(max_length=50)),
                ('taste', models.CharField(choices=[('S', 'słodki'), ('B', 'gorzki'), ('R', 'kwaśny')], default='S', max_length=2)),
                ('temperature', models.CharField(choices=[('W', 'ciepły'), ('C', 'zimny')], default='C', max_length=2)),
                ('descriptionPreparing', models.TextField(help_text='Opis przygotowania')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='składniki', to='searchdrink.drinks')),
            ],
        ),
    ]
