# Generated by Django 3.2.3 on 2021-05-28 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searchdrink', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alcohol', models.CharField(max_length=15)),
                ('otherdrink', models.CharField(max_length=15)),
                ('fruit', models.CharField(max_length=15)),
                ('otheradd', models.CharField(max_length=15)),
            ],
        ),
        migrations.RenameModel(
            old_name='Drinks',
            new_name='Drink',
        ),
        migrations.DeleteModel(
            name='Ingredients',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='drink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='składniki', to='searchdrink.drink'),
        ),
    ]
