# Generated by Django 3.2.3 on 2021-06-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchdrink', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alcohol',
            name='drink',
        ),
        migrations.RemoveField(
            model_name='fruit',
            name='drink',
        ),
        migrations.RemoveField(
            model_name='otheradd',
            name='drink',
        ),
        migrations.RemoveField(
            model_name='otherdrink',
            name='drink',
        ),
        migrations.AddField(
            model_name='drink',
            name='_alcohol',
            field=models.ManyToManyField(to='searchdrink.Alcohol'),
        ),
        migrations.AddField(
            model_name='drink',
            name='_fruit',
            field=models.ManyToManyField(to='searchdrink.Fruit'),
        ),
        migrations.AddField(
            model_name='drink',
            name='_otheradd',
            field=models.ManyToManyField(to='searchdrink.OtherAdd'),
        ),
        migrations.AddField(
            model_name='drink',
            name='_otherdrink',
            field=models.ManyToManyField(to='searchdrink.OtherDrink'),
        ),
    ]
