# Generated by Django 3.2.3 on 2021-05-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchdrink', '0002_auto_20210528_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='photo',
            field=models.ImageField(default='some photo', upload_to='uploads/'),
        ),
    ]
