# Generated by Django 3.2.3 on 2021-06-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchdrink', '0002_auto_20210604_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='_alcohol',
            field=models.ManyToManyField(blank=True, to='searchdrink.Alcohol'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='_fruit',
            field=models.ManyToManyField(blank=True, to='searchdrink.Fruit'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='_otheradd',
            field=models.ManyToManyField(blank=True, to='searchdrink.OtherAdd'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='_otherdrink',
            field=models.ManyToManyField(blank=True, to='searchdrink.OtherDrink'),
        ),
    ]
