# Generated by Django 3.2.3 on 2021-05-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchdrink', '0003_drink_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='descriptionPreparing',
            field=models.TextField(help_text='Opis przygotowania', verbose_name='Opis przygotowania'),
        ),
    ]
