# Generated by Django 3.2.3 on 2021-05-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchdrink', '0005_auto_20210528_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='otheradd',
            field=models.CharField(choices=[], max_length=15, verbose_name='Inne dodatki'),
        ),
    ]
