# Generated by Django 3.2.3 on 2021-05-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchdrink', '0006_alter_ingredient_otheradd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='fruit',
            field=models.CharField(blank=True, max_length=15, verbose_name='Owoce'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='otheradd',
            field=models.CharField(blank=True, max_length=15, verbose_name='Inne dodatki'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='otherdrink',
            field=models.CharField(blank=True, max_length=15, verbose_name='Inne napoje'),
        ),
    ]
