# Generated by Django 3.2.3 on 2021-05-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchdrink', '0008_auto_20210530_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='alcohol',
            field=models.CharField(blank=True, max_length=20, verbose_name='Alkohol'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='otheradd',
            field=models.CharField(blank=True, max_length=30, verbose_name='Inne dodatki'),
        ),
    ]
